# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\xbb\x01\n\x10InferenceRequest\x12\x12\n\ntext_input\x18\x01 \x01(\t\x12\x14\n\x0c\x61udio_prompt\x18\x02 \x01(\x0c\x12\x16\n\x0emax_new_tokens\x18\x03 \x01(\x05\x12\x11\n\tcfg_scale\x18\x04 \x01(\x02\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\r\n\x05top_p\x18\x06 \x01(\x02\x12\x18\n\x10\x63\x66g_filter_top_k\x18\x07 \x01(\x05\x12\x14\n\x0cspeed_factor\x18\x08 \x01(\x02\"M\n\x11InferenceResponse\x12\x14\n\x0c\x61udio_output\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\r\n\x05\x65rror\x18\x03 \x01(\t2^\n\x10InferenceService\x12J\n\rGenerateAudio\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=31
  _globals['_INFERENCEREQUEST']._serialized_end=218
  _globals['_INFERENCERESPONSE']._serialized_start=220
  _globals['_INFERENCERESPONSE']._serialized_end=297
  _globals['_INFERENCESERVICE']._serialized_start=299
  _globals['_INFERENCESERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
